add_rules("mode.debug", "mode.release", "mode.profile")

add_requires("libaccel-config", {system = true})
add_requires("fmt", {system = true})
add_requires("stdexec", {system = true})

set_strip("none")
set_symbols("debug")
add_ldflags("-fuse-ld=mold")

set_languages("c++23")
add_includedirs("include", "src")
add_links("stdc++exp")
add_cxxflags("-fno-omit-frame-pointer")

-- AddressSanitizer support: use `xmake f --policies=build.sanitizer.address`
option("asan")
    set_default(false)
    set_showmenu(true)
    set_description("Enable AddressSanitizer")
option_end()

if has_config("asan") then
    set_policy("build.sanitizer.address", true)
end

-- Static library: all DsaEngine template instantiations compiled once
target("libdsa")
    set_kind("static")
    add_files("src/dsa/dsa_instantiate.cpp")
    add_files("src/dsa/dsa_staging_instantiate.cpp")
    add_files("src/dsa/dsa_fixed_ring_instantiate.cpp")
    add_files("src/dsa/dsa_ring_instantiate.cpp")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")

target("dsa-stdexec")
    set_kind("binary")
    add_files("src/main.cpp")
    add_deps("libdsa")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")


target("dsa_benchmark")
    set_kind("binary")
    add_files("benchmark/dsa/main.cpp")
    add_files("benchmark/dsa/strategy_sliding_window.cpp")
    add_files("benchmark/dsa/strategy_noalloc.cpp")
    add_files("benchmark/dsa/strategy_arena.cpp")
    add_files("benchmark/dsa/strategy_batch.cpp")
    add_files("benchmark/dsa/strategy_batch_noalloc.cpp")
    add_files("benchmark/dsa/strategy_scoped_workers.cpp")
    add_files("benchmark/dsa/strategy_batch_raw.cpp")
    add_files("benchmark/dsa/config.cpp")
    add_includedirs("benchmark/dsa")
    add_deps("libdsa")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")


target("dsa_benchmark_static")
    set_default(false)
    set_kind("binary")
    add_files("benchmark/dsa/static.cpp")
    add_files("benchmark/dsa/config.cpp")
    add_includedirs("benchmark/dsa")
    add_deps("libdsa")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")


target("dsa_launcher")
    set_kind("binary")
    set_languages("c11")
    add_files("tools/dsa_launcher.c")
    add_links("cap")
    set_default(false)
    after_build(function (target)
        os.exec("sudo setcap cap_sys_rawio+eip " .. target:targetdir() .. "/dsa_launcher")
    end)

target("task_queue_benchmark")
    set_kind("binary")
    add_files("benchmark/task_queue/main.cpp")
    add_packages("fmt")
    add_packages("stdexec")

-- Examples
for _, name in ipairs({"data_move", "mem_fill", "compare", "compare_value", "dualcast", "crc_gen", "copy_crc", "cache_flush"}) do
    target("example_" .. name)
        set_kind("binary")
        add_files("examples/" .. name .. ".cpp")
        add_deps("libdsa")
        add_packages("libaccel-config")
        add_packages("fmt")
        add_packages("stdexec")
        add_cflags("-menqcmd")
        add_cxxflags("-menqcmd")
        add_cflags("-movdir64b")
        add_cxxflags("-mmovdir64b")
end
