add_rules("mode.debug", "mode.release", "mode.profile")

add_requires("libaccel-config", {system = true})
add_requires("fmt", {system = true})
add_requires("stdexec", {system = true})

set_languages("c++23")
add_includedirs("include", "src")
add_links("stdc++exp")

target("dsa-stdexec")
    set_kind("binary")
    add_files("src/**.cpp")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    -- add_packages("proxy")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")
    after_build(function (target)
        os.exec("sudo setcap cap_sys_rawio+ep " .. target:targetdir() .. "/dsa-stdexec")
    end)


target("dsa_benchmark")
    set_kind("binary")
    add_files("benchmark/dsa_benchmark.cpp")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")
    add_files("src/dsa/dsa_instantiate.cpp")
    after_build(function (target)
        os.exec("sudo setcap cap_sys_rawio+ep " .. target:targetdir() .. "/dsa_benchmark")
    end)
