[
  {
    "dev":"iax1",
    "groups":[
      {
        "dev":"group1.0",
        "grouped_workqueues":[
          {
            "dev":"wq1.0",
            "mode":"dedicated",
            "size":128,
            "group_id":0,
            "priority":10,
            "block_on_fault":0,
            "max_transfer_size":2097152,
            "type":"user",
            "name":"hw_eval_iax",
            "driver_name":"user",
            "threshold":0,
            "ats_disable":-2
          }
        ],
        "grouped_engines":[
          {
            "dev":"engine1.0",
            "group_id":0
          }
        ]
      }
    ]
  },
  {
    "dev":"iax3",
    "groups":[
      {
        "dev":"group3.0",
        "grouped_workqueues":[
          {
            "dev":"wq3.0",
            "mode":"dedicated",
            "size":128,
            "group_id":0,
            "priority":10,
            "block_on_fault":0,
            "max_transfer_size":2097152,
            "type":"user",
            "name":"hw_eval_iax",
            "driver_name":"user",
            "threshold":0,
            "ats_disable":-2
          }
        ],
        "grouped_engines":[
          {
            "dev":"engine3.0",
            "group_id":0
          }
        ]
      }
    ]
  }
]
