add_rules("mode.debug", "mode.release", "mode.profile")

add_requires("libaccel-config", {system = true})
add_requires("fmt", {system = true})
add_requires("stdexec", {system = true})

set_strip("none")
set_symbols("debug")
add_ldflags("-fuse-ld=mold")

set_languages("c++23")
add_includedirs("include", "src")
add_links("stdc++exp")
add_cxxflags("-fno-omit-frame-pointer")

-- AddressSanitizer support: use `xmake f --policies=build.sanitizer.address`
option("asan")
    set_default(false)
    set_showmenu(true)
    set_description("Enable AddressSanitizer")
option_end()

if has_config("asan") then
    set_policy("build.sanitizer.address", true)
end

-- Static library: all DsaEngine template instantiations compiled once
target("libdsa")
    set_kind("static")
    add_files("src/dsa/dsa_instantiate.cpp")
    add_files("src/dsa/dsa_staging_instantiate.cpp")
    add_files("src/dsa/dsa_fixed_ring_instantiate.cpp")
    add_files("src/dsa/dsa_ring_instantiate.cpp")
    add_files("src/dsa/dsa_mirrored_ring_instantiate.cpp")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")

target("dsa-stdexec")
    set_kind("binary")
    add_files("src/main.cpp")
    add_deps("libdsa")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")


target("dsa_benchmark")
    set_kind("binary")
    add_files("benchmark/dsa/main.cpp")
    -- Sliding window strategies
    add_files("benchmark/dsa/strategies/sliding_window/sliding_window.cpp")
    add_files("benchmark/dsa/strategies/sliding_window/noalloc.cpp")
    add_files("benchmark/dsa/strategies/sliding_window/arena.cpp")
    add_files("benchmark/dsa/strategies/sliding_window/direct.cpp")
    add_files("benchmark/dsa/strategies/sliding_window/reusable.cpp")
    -- Batch strategies
    add_files("benchmark/dsa/strategies/batch/heap_alloc.cpp")
    add_files("benchmark/dsa/strategies/batch/noalloc.cpp")
    add_files("benchmark/dsa/strategies/batch/raw.cpp")
    -- Scoped workers
    add_files("benchmark/dsa/strategies/scoped_workers/scoped_workers.cpp")
    add_files("benchmark/dsa/config.cpp")
    add_includedirs("benchmark/dsa")
    add_deps("libdsa")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")


target("dsa_benchmark_static")
    set_default(false)
    set_kind("binary")
    add_files("benchmark/dsa/static.cpp")
    add_files("benchmark/dsa/config.cpp")
    add_includedirs("benchmark/dsa")
    add_deps("libdsa")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")


target("task_queue_benchmark")
    set_kind("binary")
    add_files("benchmark/task_queue/main.cpp")
    add_packages("fmt")
    add_packages("stdexec")

-- Tests (requires dsa_launcher for CAP_SYS_RAWIO)
target("test_mirrored_ring")
    set_kind("binary")
    set_default(false)
    add_files("test/test_mirrored_ring.cpp")
    add_deps("libdsa")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")
    add_tests("mirrored_ring", {run_timeout = 30000})
    on_test(function (target)
        local launcher = path.join(os.projectdir(), "..", "tools", "build", "dsa_launcher")
        local testbin = target:targetfile()
        os.execv(launcher, {testbin})
        return true
    end)

-- Unit tests (no hardware required, use mocks)
target("test_task_queues")
    set_kind("binary")
    set_default(false)
    add_files("test/test_task_queues.cpp")
    add_includedirs("test")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")
    add_tests("task_queues")

target("test_stdexec_integration")
    set_kind("binary")
    set_default(false)
    add_files("test/test_stdexec_integration.cpp")
    add_includedirs("test")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")
    add_tests("stdexec_integration")

target("test_utilities")
    set_kind("binary")
    set_default(false)
    add_files("test/test_utilities.cpp")
    add_includedirs("test")
    add_packages("fmt")
    add_packages("stdexec")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")
    add_tests("utilities")

-- Examples
for _, name in ipairs({"data_move", "mem_fill", "compare", "compare_value", "dualcast", "crc_gen", "copy_crc", "cache_flush"}) do
    target("example_" .. name)
        set_kind("binary")
        add_files("examples/" .. name .. ".cpp")
        add_deps("libdsa")
        add_packages("libaccel-config")
        add_packages("fmt")
        add_packages("stdexec")
        add_cflags("-menqcmd")
        add_cxxflags("-menqcmd")
        add_cflags("-movdir64b")
        add_cxxflags("-mmovdir64b")
end
